package authzgen

// clientTemplate generates client.gen.go.
// Template data: struct{ Package string }
const clientTemplate = `// Code generated by authzed-codegen. DO NOT EDIT.
package {{.Package}}

import (
	"fmt"

	"github.com/authzed/authzed-go/v1"
	"github.com/authzed/grpcutil"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// Base types shared across all definition files.
type Type string
type Relation string
type Permission string
type ID string

// Client wraps authzed.ClientWithExperimental.
type Client struct {
	*authzed.ClientWithExperimental
}

// clientOptions holds configuration for the AuthZed client.
type clientOptions struct {
	endpoint string
	token    string
	port     string
	insecure bool
}

// ClientOption is a functional option for configuring the AuthZed client.
type ClientOption func(*clientOptions)

// WithEndpoint sets the AuthZed endpoint.
func WithEndpoint(endpoint string) ClientOption {
	return func(o *clientOptions) { o.endpoint = endpoint }
}

// WithPort sets the AuthZed port.
func WithPort(port string) ClientOption {
	return func(o *clientOptions) { o.port = port }
}

// WithToken sets the AuthZed authentication token.
func WithToken(token string) ClientOption {
	return func(o *clientOptions) { o.token = token }
}

// WithInsecure enables insecure connection (for development only).
func WithInsecure(insecure bool) ClientOption {
	return func(o *clientOptions) { o.insecure = insecure }
}

// NewClient creates a new Client. Call once at startup; pass the result to
// each store constructor (e.g. NewDoctypeStore, NewTeamStore).
func NewClient(opts ...ClientOption) (*Client, error) {
	config := &clientOptions{
		port:     "50051",
		insecure: true,
	}
	for _, opt := range opts {
		opt(config)
	}
	if config.endpoint == "" || config.token == "" {
		return nil, fmt.Errorf("endpoint and token are required")
	}
	return newClient(config)
}

func newClient(config *clientOptions) (*Client, error) {
	var dialOpts []grpc.DialOption
	if config.insecure {
		dialOpts = append(dialOpts, grpc.WithTransportCredentials(insecure.NewCredentials()))
	}
	dialOpts = append(dialOpts, grpcutil.WithInsecureBearerToken(config.token))
	client, err := authzed.NewClientWithExperimentalAPIs(
		fmt.Sprintf("%s:%s", config.endpoint, config.port),
		dialOpts...,
	)
	if err != nil {
		return nil, err
	}
	return &Client{client}, nil
}
`

// definitionTemplate generates <name>.gen.go for a single definition.
// Template data: struct{ Package string; Definition Definition }
const definitionTemplate = `// Code generated by authzed-codegen. DO NOT EDIT.
package {{.Package}}

import (
{{- if or .Definition.Relations .Definition.Permissions}}
	"context"
	"errors"
	"io"
{{- end}}
	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
)

{{$def := .Definition}}
{{$defName := .Definition.Name | camelcase}}

// Type & constants 

const Type{{$defName}} Type = "{{$def.Name}}"

type Relation{{$defName}} string
type Permission{{$defName}} string

{{range $def.Relations -}}
const {{$defName}}{{.Name | camelcase}}Rel Relation{{$defName}} = "{{.Name}}"
{{end -}}
{{range $def.Permissions -}}
const {{$defName}}{{.Name | camelcase}}Perm Permission{{$defName}} = "{{.Name}}"
{{end}}
// Objects structs 

{{range $def.Relations -}}
{{$relName := .Name | camelcase -}}
// {{$defName}}{{$relName}}Objects holds the typed subjects for the {{.Name}} relation.
type {{$defName}}{{$relName}}Objects struct {
{{range .Types}}	{{. | extractType | camelcase}} []{{. | extractType | camelcase}} ` + "`" + `json:"{{. | extractType}},omitempty"` + "`" + `
{{end}}}

{{end}}
// Resource ID type 

// {{$defName}} is the strongly-typed resource ID for a {{$def.Name}} object.
type {{$defName}} string

func New{{$defName}}(id string) {{$defName}} { return {{$defName}}(id) }

func (r {{$defName}}) String() string { return string(r) }

func (r {{$defName}}) ResourceReference() *v1.ObjectReference {
	return &v1.ObjectReference{
		ObjectType: string(Type{{$defName}}),
		ObjectId:   string(r),
	}
}

// Store interface 

// {{$defName}}StoreInterface lists every method on {{$defName}}Store; use it to inject mocks in tests.
type {{$defName}}StoreInterface interface {
{{range $def.Relations -}}
{{$relName := .Name | camelcase}}
	Create{{$relName}}Relations(ctx context.Context, id {{$defName}}, objects {{$defName}}{{$relName}}Objects) error
	Delete{{$relName}}Relations(ctx context.Context, id {{$defName}}, objects {{$defName}}{{$relName}}Objects) error
	Read{{$relName}}Relations(ctx context.Context, id {{$defName}}) ({{$defName}}{{$relName}}Objects, error)
{{end -}}
{{range $def.Permissions -}}
{{$permName := .Name | camelcase}}
	Check{{$permName}}(ctx context.Context, id {{$defName}}, subject *v1.SubjectReference) (bool, error)
	Lookup{{$permName}}Subjects(ctx context.Context, id {{$defName}}, subjectType string) ([]string, error)
	Lookup{{$permName}}Resources(ctx context.Context, subject *v1.SubjectReference) ([]{{$defName}}, error)
{{end -}}
}

// Store struct & constructor

// {{$defName}}Store provides type-safe SpiceDB methods for the {{$def.Name}} definition.
type {{$defName}}Store struct {
	client *Client
}

// New{{$defName}}Store creates a {{$defName}}Store backed by the given Client.
func New{{$defName}}Store(client *Client) *{{$defName}}Store {
	return &{{$defName}}Store{client: client}
}

//  Relation methods

{{range $def.Relations}}
{{$relName := .Name | camelcase}}
{{$types := .Types}}

// Create{{$relName}}Relations writes CREATE updates for the {{.Name}} relation on id.
func (s *{{$defName}}Store) Create{{$relName}}Relations(ctx context.Context, id {{$defName}}, objects {{$defName}}{{$relName}}Objects) error {
	var updates []*v1.RelationshipUpdate
{{range $types}}
	for _, obj := range objects.{{. | extractType | camelcase}} {
		updates = append(updates, &v1.RelationshipUpdate{
			Operation: v1.RelationshipUpdate_OPERATION_CREATE,
			Relationship: &v1.Relationship{
				Resource: id.ResourceReference(),
				Relation: string({{$defName}}{{$relName}}Rel),
				Subject:  &v1.SubjectReference{Object: obj.ResourceReference()},
			},
		})
	}
{{end}}
	if len(updates) == 0 {
		return nil
	}
	_, err := s.client.WriteRelationships(ctx, &v1.WriteRelationshipsRequest{Updates: updates})
	return err
}

// Delete{{$relName}}Relations writes DELETE updates for the {{.Name}} relation on id.
func (s *{{$defName}}Store) Delete{{$relName}}Relations(ctx context.Context, id {{$defName}}, objects {{$defName}}{{$relName}}Objects) error {
	var updates []*v1.RelationshipUpdate
{{range $types}}
	for _, obj := range objects.{{. | extractType | camelcase}} {
		updates = append(updates, &v1.RelationshipUpdate{
			Operation: v1.RelationshipUpdate_OPERATION_DELETE,
			Relationship: &v1.Relationship{
				Resource: id.ResourceReference(),
				Relation: string({{$defName}}{{$relName}}Rel),
				Subject:  &v1.SubjectReference{Object: obj.ResourceReference()},
			},
		})
	}
{{end}}
	if len(updates) == 0 {
		return nil
	}
	_, err := s.client.WriteRelationships(ctx, &v1.WriteRelationshipsRequest{Updates: updates})
	return err
}

// Read{{$relName}}Relations reads all subjects for the {{.Name}} relation on id.
func (s *{{$defName}}Store) Read{{$relName}}Relations(ctx context.Context, id {{$defName}}) ({{$defName}}{{$relName}}Objects, error) {
	var result {{$defName}}{{$relName}}Objects
	stream, err := s.client.ReadRelationships(ctx, &v1.ReadRelationshipsRequest{
		Consistency: &v1.Consistency{Requirement: &v1.Consistency_FullyConsistent{FullyConsistent: true}},
		RelationshipFilter: &v1.RelationshipFilter{
			ResourceType:       string(Type{{$defName}}),
			OptionalResourceId: string(id),
			OptionalRelation:   string({{$defName}}{{$relName}}Rel),
		},
	})
	if err != nil {
		return result, err
	}
	for {
		resp, err := stream.Recv()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return result, err
		}
		subject := resp.Relationship.Subject.Object
		switch subject.ObjectType {
{{range $types}}		case string(Type{{. | extractType | camelcase}}):
			result.{{. | extractType | camelcase}} = append(result.{{. | extractType | camelcase}}, {{. | extractType | camelcase}}(subject.ObjectId))
{{end}}		}
	}
	return result, nil
}
{{end}}

//Permission methods 

{{range $def.Permissions}}
{{$permName := .Name | camelcase}}

// Check{{$permName}} returns true when subject has {{.Name}} permission on id.
func (s *{{$defName}}Store) Check{{$permName}}(ctx context.Context, id {{$defName}}, subject *v1.SubjectReference) (bool, error) {
	resp, err := s.client.CheckPermission(ctx, &v1.CheckPermissionRequest{
		Resource:   id.ResourceReference(),
		Permission: string({{$defName}}{{$permName}}Perm),
		Subject:    subject,
	})
	if err != nil {
		return false, err
	}
	return resp.Permissionship == v1.CheckPermissionResponse_PERMISSIONSHIP_HAS_PERMISSION, nil
}

// Lookup{{$permName}}Subjects returns IDs of subjects of subjectType that have {{.Name}} permission on id.
func (s *{{$defName}}Store) Lookup{{$permName}}Subjects(ctx context.Context, id {{$defName}}, subjectType string) ([]string, error) {
	var subjects []string
	stream, err := s.client.LookupSubjects(ctx, &v1.LookupSubjectsRequest{
		Consistency:       &v1.Consistency{Requirement: &v1.Consistency_FullyConsistent{FullyConsistent: true}},
		Resource:          id.ResourceReference(),
		Permission:        string({{$defName}}{{$permName}}Perm),
		SubjectObjectType: subjectType,
	})
	if err != nil {
		return nil, err
	}
	for {
		resp, err := stream.Recv()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, err
		}
		subjects = append(subjects, resp.Subject.SubjectObjectId)
	}
	return subjects, nil
}

// Lookup{{$permName}}Resources returns all {{$def.Name}} IDs where subject has {{.Name}} permission.
func (s *{{$defName}}Store) Lookup{{$permName}}Resources(ctx context.Context, subject *v1.SubjectReference) ([]{{$defName}}, error) {
	var resources []{{$defName}}
	stream, err := s.client.LookupResources(ctx, &v1.LookupResourcesRequest{
		Consistency:        &v1.Consistency{Requirement: &v1.Consistency_FullyConsistent{FullyConsistent: true}},
		ResourceObjectType: string(Type{{$defName}}),
		Permission:         string({{$defName}}{{$permName}}Perm),
		Subject:            subject,
	})
	if err != nil {
		return nil, err
	}
	for {
		resp, err := stream.Recv()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, err
		}
		resources = append(resources, {{$defName}}(resp.ResourceObjectId))
	}
	return resources, nil
}
{{end}}
`
